### ISSUE TITLE
How to use multi Rx/Tx queue ?

### ISSUE THREAD

**Issue by 490** [marty90/DPDK-Dump#8]
Hi,
Thank you for your DPDK-Dump app,I want to improve this app's capability.
1、Now I have a intel nic
![image](https://cloud.githubusercontent.com/assets/11677298/25082777/8eda93ee-2385-11e7-9d5e-0d8303bc63ba.png)
how can I set up the number of rx/tx queue with the function rte_eth_dev_configure or rte_eth_rx_queue_setup? I tried to change the parameters in your app but it didn't work.
2、My computer have 256 lcores,can I use all of them to  achieve the performence limit?
3、Do you know nDPI(deep packet inspection)?How can I combine nDPI with your app?
Could you please to give some advice for me ?
Thank you very much!

**Comment by marty90** [comment]
1) DPDK-Dump writes on disk the traffic it captures. Thus, no matter how many cores/queues you have. The bottleneck is the disk. I recommend to use a RAID0 array of SSDs for high performance.
2) DPDK-Dump always uses 2 cores.
3) If you want to analyse the traffic instead of dumping it on disk, you can use Tstat-DPDK [(here)](http://tstat.polito.it/viewvc/software/tstat/branches/tstat-dpdk/README.html?view=co). It scales with the number of cores of your machine. We tested it at 40Gbps live traffic. It performs DPI and statistical analysis on the incoming traffic and aggregates it into flows (TCP and UDP).

**Comment by 490** [comment]
Thank you!!
